import Head from 'next/head';
import styled from 'styled-components';
import withAuth from './Auth/withAuth';

const Hero = styled.div`
  height: 90vh;
  display: flex;
  justify-content: center;
  align-items: center;
  background: #fff;
`;

const Heading = styled.h1`
  color: #000;
  font-size: 10rem;
  font-weight: 900;
`;

function Home() {
  return (
    <>
      <Head>
        <title>Dashboard</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Hero>
        <Heading>Next</Heading>
      </Hero>
    </>
  );
}

export default withAuth(Home);
